# Generated by Django 3.0 on 2021-05-25 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uuidgenerator',
            name='name',
        ),
    ]
