# Generated by Django 3.0 on 2021-05-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapi', '0002_remove_uuidgenerator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuidgenerator',
            name='uuid',
            field=models.UUIDField(default='7f2129730d9b4f3e8550103a637194fa', unique=True),
        ),
    ]
